repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        entry: clang-format -i
        args: ["-style=file"]
        language: system
        types: [c++]
